/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

/**
 *
 * @author Admin
 */
import common.Message;
import common.MessageType;
import java.io.IOException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.JOptionPane;

public class VoiceCallFrame extends javax.swing.JFrame {

    /**
     * Creates new form VoiceCallFrame
     */
    private String username;
    private String otherUser;
    private ClientConnection connection;
    private VoiceCallManager voiceCallManager;
    private boolean incomingCall;
    private Runnable onCloseCallback;

    private Thread recordingThread;
    private Thread playbackThread;
    private final BlockingQueue<byte[]> audioQueue = new LinkedBlockingQueue<>();
    private volatile boolean inCall = false;

    // Constructor mặc định cho NetBeans
    public VoiceCallFrame() {
        initComponents();
    }

    // Constructor dùng cho cuộc gọi (không có callback)
    public VoiceCallFrame(
            String username,
            String otherUser,
            ClientConnection connection,
            boolean incomingCall) {
        this(username, otherUser, connection, incomingCall, null);
    }

    // Constructor đầy đủ có callback khi đóng cuộc gọi
    public VoiceCallFrame(
            String username,
            String otherUser,
            ClientConnection connection,
            boolean incomingCall,
            Runnable onCloseCallback) {

        initComponents();

        this.username = username;
        this.otherUser = otherUser;
        this.connection = connection;
        this.incomingCall = incomingCall;
        this.onCloseCallback = onCloseCallback;

        this.voiceCallManager = new VoiceCallManager();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                handleWindowClosing();
            }
        });

        setLocationRelativeTo(null);
        setTitle("Cuộc gọi thoại - " + otherUser);

        lb_callername.setText(otherUser);

        if (incomingCall) {
            // Người nhận cuộc gọi
            lb_callstatus.setText("Đang gọi đến...");

            btnAccept.setVisible(true);
            btnReject.setVisible(true);
            btnEndCall.setVisible(false);

        } else {
            // Người thực hiện cuộc gọi
            lb_callstatus.setText("Đang gọi...");

            btnAccept.setVisible(false);
            btnReject.setVisible(false);
            btnEndCall.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_call = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_callername = new javax.swing.JLabel();
        lb_callstatus = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnEndCall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_call.setText("cuộc gọi thọại");

        lb_callername.setText("name");

        lb_callstatus.setText("đang gọi đến .....");

        btnAccept.setText("chấp nhận ");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("từ chối ");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnEndCall.setText("kết thúc");
        btnEndCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndCallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_callstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lb_call)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(lb_callername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnAccept)
                        .addGap(95, 95, 95)
                        .addComponent(btnReject))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnEndCall)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lb_call)
                .addGap(38, 38, 38)
                .addComponent(lb_callername)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_callstatus)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnEndCall)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        acceptCall();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        rejectCall();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnEndCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndCallActionPerformed
        // TODO add your handling code here:
        endCall();
    }//GEN-LAST:event_btnEndCallActionPerformed
    private synchronized void startVoiceStreams() {
        if (inCall) {
            return;
        }
        try {
            voiceCallManager.start();
            inCall = true;
        } catch (LineUnavailableException e) {
            JOptionPane.showMessageDialog(this, "Không thể mở microphone hoặc loa: " + e.getMessage());
            endCall();
            return;
        }

        // Thread phát âm thanh từ audioQueue ra loa
        playbackThread = new Thread(() -> {
            while (inCall && voiceCallManager != null && voiceCallManager.isRunning()) {
                try {
                    byte[] data = audioQueue.poll(100, TimeUnit.MILLISECONDS);
                    if (data != null && inCall) {
                        voiceCallManager.playAudio(data);
                    }
                } catch (InterruptedException e) {
                    break;
                }
            }
        }, "Voice-Playback-Thread");
        playbackThread.setDaemon(true);
        playbackThread.start();

        // Thread đọc mic và gửi qua socket
        recordingThread = new Thread(() -> {
            while (inCall && voiceCallManager != null && voiceCallManager.isRunning()) {
                byte[] audio = voiceCallManager.readMicrophone();
                if (audio != null && audio.length > 0 && inCall) {
                    Message audioMsg = new Message(MessageType.VOICE_DATA, username, null);
                    audioMsg.setReceiver(otherUser);
                    audioMsg.setVoiceData(audio);
                    try {
                        connection.send(audioMsg);
                    } catch (IOException e) {
                        System.out.println("Không thể gửi gói thoại: " + e.getMessage());
                        break;
                    }
                }
            }
        }, "Voice-Record-Thread");
        recordingThread.setDaemon(true);
        recordingThread.start();
    }

    public void receiveAudio(byte[] data) {
        if (inCall && data != null && data.length > 0) {
            audioQueue.offer(data);
        }
    }

    private synchronized void stopVoiceStreams() {
        inCall = false;
        if (recordingThread != null) {
            recordingThread.interrupt();
            recordingThread = null;
        }
        if (playbackThread != null) {
            playbackThread.interrupt();
            playbackThread = null;
        }
        audioQueue.clear();
        if (voiceCallManager != null) {
            voiceCallManager.stop();
        }
    }

    private void handleWindowClosing() {
        if (incomingCall && !inCall) {
            rejectCall();
        } else {
            endCall();
        }
    }

    private void endCall() {
        Message message = new Message(
                MessageType.CALL_END,
                username,
                "Ended"
        );
        message.setReceiver(otherUser);

        try {
            connection.send(message);
        } catch (IOException e) {
            System.out.println(
                    "Không thể gửi CALL_END: " + e.getMessage()
            );
        }

        stopVoiceStreams();
        if (onCloseCallback != null) {
            onCloseCallback.run();
        }
        dispose();
    }

    private void rejectCall() {
        Message message = new Message(
                MessageType.CALL_REJECT,
                username,
                "Rejected"
        );
        message.setReceiver(otherUser);

        try {
            connection.send(message);
            lb_callstatus.setText("Đã từ chối cuộc gọi.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Không thể từ chối cuộc gọi: " + e.getMessage()
            );
        }

        stopVoiceStreams();
        if (onCloseCallback != null) {
            onCloseCallback.run();
        }
        dispose();
    }

    private void acceptCall() {
        Message message = new Message(
                MessageType.CALL_ACCEPT,
                username,
                "Accepted"
        );
        message.setReceiver(otherUser);

        try {
            connection.send(message);

            lb_callstatus.setText("Đang trong cuộc gọi...");
            btnAccept.setVisible(false);
            btnReject.setVisible(false);
            btnEndCall.setVisible(true);

            startVoiceStreams();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Không thể chấp nhận cuộc gọi: " + e.getMessage()
            );
        }
    }

    public void callAccepted() {
        lb_callstatus.setText("Đang trong cuộc gọi...");
        btnAccept.setVisible(false);
        btnReject.setVisible(false);
        btnEndCall.setVisible(true);

        startVoiceStreams();
    }

    public void callRejected() {
        lb_callstatus.setText("Cuộc gọi bị từ chối.");
        stopVoiceStreams();
        if (onCloseCallback != null) {
            onCloseCallback.run();
        }
        dispose();
    }

    public void callEnded() {
        lb_callstatus.setText("Cuộc gọi đã kết thúc.");
        stopVoiceStreams();
        if (onCloseCallback != null) {
            onCloseCallback.run();
        }
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoiceCallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoiceCallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoiceCallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoiceCallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoiceCallFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnEndCall;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_call;
    private javax.swing.JLabel lb_callername;
    private javax.swing.JLabel lb_callstatus;
    // End of variables declaration//GEN-END:variables
}
